### PR TITLE
Parse true and false as identifiers in mssql

### PR DESCRIPTION
**Pull request by lovasoa**
fixes https://github.com/apache/datafusion-sqlparser-rs/issues/1508

### CODE REVIEW

**Comment by lovasoa** [comment]
There are 7 failing tests at the moment. From a quick glance, it looks like it's the tests that are incorrect: they rely on the existence of boolean literals in all dialects.

**Comment by lovasoa** [comment]
Ok, I fixed all the tests, this is ready for review @iffyio, @alamb :)

**Comment by lovasoa** [comment]
@alamb : Sorry ! It's fixed now.

**Comment by alamb** [comment]
🤔  I don't know why but this repo now seems to require manually starting CI. I will look into it

**Comment by git-hulk** [comment]
@alamb It's the Apache organization setting that requires if my memory serves.

**Comment by alamb** [comment]
I have filed https://issues.apache.org/jira/browse/INFRA-26268 for trying to ensure CI runs automatically

**Comment by alamb** [comment]
> @alamb It's the Apache organization's setting behavior if my memory serves. All repositories in the organization are required to manually trigger CI for non-members.

Thanks @git-hulk  -- arrow and DataFusion both are set to run CI after the first time a contributor has had a PR merged. I filed https://issues.apache.org/jira/browse/INFRA-26268 to request the same setting on this repository (what it used to be as well)

**Pull request merged**
