### PR TITLE
support `json_object('k':'v')` in postgres

### PR DESCRIPTION
**Pull request by lovasoa**
This just updates the postgres dialect definition to add support for the json_object syntax added in https://github.com/apache/datafusion-sqlparser-rs/pull/1507

The syntax was initially added for mssql but also works in postgres

See https://www.postgresql.org/docs/current/functions-json.html

See https://github.com/apache/datafusion-sqlparser-rs/issues/1545

support for `json_object('k' VALUE 'v')` is implemented [in a separate PR](https://github.com/apache/datafusion-sqlparser-rs/pull/1547)

### CODE REVIEW

**Comment by lovasoa** [comment]
I moved the corresponding tests from `tests/sqlparser_mssql.rs` to `tests/sqlparser_common.rs`

**Review by alamb — APPROVED** [review]
Thanks @lovasoa

**Review by iffyio — APPROVED** [review]
LGTM!

**Comment by alamb** [comment]
🚀  -- thanks again

**Comment by lovasoa** [comment]
Great ! https://github.com/apache/datafusion-sqlparser-rs/pull/1547 should now be mergeable upon rebase

**Pull request merged**
