### PR TITLE
Fix typo in `Dialect::supports_eq_alias_assigment`

### PR DESCRIPTION
**Pull request by alamb**
I noticed this while reviewing other PRs. I think it is a small typo introduced in #1467

FYI @yoavcloud

### CODE REVIEW

**Comment by alamb** [comment]
Screenshot 2024-10-21 at 2 56 05 PM

**Comment by yoavcloud** [comment]
Thanks!

**Review by iffyio — APPROVED** [review]
Ah thanks for catching and fixing this @alamb! LGTM!

**Comment by alamb** [comment]
🤔  something is not working with permissions and I can't merge PRs anymore (I think it is because someone else with write access needs to approve the PR):

Screenshot 2024-10-26 at 7 15 39 AM

I think this changed in https://github.com/apache/datafusion-sqlparser-rs/pull/1463 from @Xuanwo  -- I will try and sort it out

**Review by iffyio — APPROVED** [review]

**Pull request merged**
